

















































 99%|█████████▉| 475/478 [01:45<00:00,  5.05batch/s]

100%|██████████| 478/478 [01:46<00:00,  4.49batch/s]
Eval Epoch 0 loss=0.48 acc=0.87
























 97%|█████████▋| 465/478 [00:48<00:01,  9.54batch/s]

100%|██████████| 478/478 [00:49<00:00,  9.61batch/s]
Eval Epoch 1 loss=0.50 acc=0.85
........
y shape: torch.Size([128, 2])
y_ shape: torch.Size([128, 2])
Traceback (most recent call last):
  File "src/main.py", line 333, in <module>
    my_model = train_model(config)
  File "src/main.py", line 226, in train_model
    loss, acc, pre, recall, f1, cm = eval_single_epoch(my_model, test_loader, config, test=True)
  File "src/main.py", line 89, in eval_single_epoch
    print(f"pred shape: {pred.shape()}")
TypeError: 'tuple' object is not callable